### ISSUE TITLE
Report Incident Form

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#32]
Figma link: https://www.figma.com/file/1JldbWl3Pe6fir7V3aMotw/Pet-Poison-Alert-Figma-Design?node-id=57-942&t=aje9IqoH84t1Nxgq-4

Create the components and the view for reporting a new incident to the map with the location. This view should be displayed when the user clicks on the big middle button in the bottom nav bar.

There's a separate ticket for the location search component that can be integrated into this component. A simple version can suffice for now it's not yet complete. See https://github.com/TeamPetPoison/pet-poison-alert/issues/17

We won't persist the data to the firebase DB just yet, but we can persist the data to local storage and populate the map with the markers from local storage or some static data for now.

For the global store we'll probably want to use the zustand store, but if it's not yet setup we can integrate it later. See https://github.com/TeamPetPoison/pet-poison-alert/issues/18

Updated Figma
![image](https://user-images.githubusercontent.com/52614742/231661406-1e415f6e-c349-40c7-a928-84b540365c2c.png)

**Comment by toreylittlefield** [comment]
@ranegray you want to give this a crack?

**Comment by ranegray** [comment]
For this I thought it might be a cool idea to let users select a location in the map and then fill out a form with more details.  Instead of location last. what do you think?

**Comment by toreylittlefield** [comment]
@ranegray sure man see the figma file. I wrote some comments on there. Give it your go.
