### ISSUE TITLE
Setup Firebase account

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#6]
We'll need to create a firebase account and setup billing alerts all that crap, fire DB, hosting. Need to create a new project there and get the `env` variables we'll need for the nextjs config.

https://firebase.google.com/docs/firestore
https://firebase.google.com/docs/hosting/nextjs#serve_fully_dynamic_content_ssr

**Comment by ranegray** [comment]
i've installed and added the config file. initialized the firebase with hosting but haven't deployed anything yet or setup billing. I thought maybe that stuff could wait. 🤷‍♂️

**Comment by MacAndersonUche** [comment]
Please those values in the firebase.js shouldn't be visible

You should store them as env variables

**Comment by ranegray** [comment]
@MacAndersonUche followed a tutorial for Next.js env file, should be good now.

**Comment by toreylittlefield** [comment]
@ranegray sent my email.
