### ISSUE TITLE
Map in form needs to integrate search api

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#62]
In the map view in the report form, the search component is a dummy component and should be swapped with the current working implementation.

Additionally its worth investigating whether the the application needs 2 separate Map view components or it can just reuse one.

**Comment by HarshMakadiya** [comment]
Hey there, I am interested in working on this issue. If possible can you assign it to me?

**Comment by toreylittlefield** [comment]
@HarshMakadiya you got it! Thank you

**Comment by toreylittlefield** [comment]
There's an existing component for location search 
packages/client/lib/components/LocationSearch.jsx

**Comment by HarshMakadiya** [comment]
@toreylittlefield Thanks for assigning this issue to me! So to clarify the issue, Whenever we click on report your incident there is 
Update the location button and, upon clicking, that the map's search bar is static and should be dynamic. Am I right?

**Comment by HarshMakadiya** [comment]
Hey @toreylittlefield I have created a PR for this issue please look into it and if there is any work that needs to be done, please tell me. me

**Comment by HarshMakadiya** [comment]
@toreylittlefield any updates Regarding the PR?

**Comment by toreylittlefield** [comment]
@HarshMakadiya I am on it 👍👍

**Comment by HarshMakadiya** [comment]
@toreylittlefield Thanks for this opportunity to work on this issue, sorry for the late reply I was outside the town 😅. Is there anything I can help with??

**Comment by toreylittlefield** [comment]
@HarshMakadiya thanks again. Sure there's always new issues to work on if you'd like and contributes are most welcome! 🙏
