### ISSUE TITLE
Firebase Nextjs Config

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#7]
Requires #6 

Scaffold the Nextjs / Firebase config in the nextjs app. Use the firebase env variables.

https://firebase.google.com/docs/hosting/nextjs#serve_fully_dynamic_content_ssr

**Comment by ranegray** [comment]
I might have done this along with #6 , didn't see this one here.

**Comment by MacAndersonUche** [comment]
Okay @toreylittlefield  take a look please

**Comment by toreylittlefield** [comment]
@ranegray @MacAndersonUche closing as https://github.com/TeamPetPoison/pet-poison-alert/pull/10
Thank you 🚀
