### ISSUE TITLE
Setup Leaflet and React Leaflet

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#8]
In the nextjs app we'll need leaflet.js and react-leaflet installed and up in working. 

When the nextjs application loads the default center of the map should be for now which should display a bit of Bali, ID on the map.

```JS
const defaultCenter = [-8.7445,115.1820];
const defaultZoom = 11;
```

**Comment by ranegray** [comment]
https://github.com/colbyfayock/next-leaflet-starter

found a starter file. i'll just put it here for future reference.

**Comment by MacAndersonUche** [comment]
@toreylittlefield  Is this ticket just a case of installing leaflet and react-leaflet and setting up the config files? or do we need to create the Map component

**Comment by ranegray** [comment]
Map is loading. Just looks like ass and I'm getting type errors. Tried installing types for leaflet but it doesn't seem to be registering them in my IDE.

**Comment by toreylittlefield** [comment]
@ranegray i'll take a look. In the future you can leave those comments on the branch itself unless you want to include them here for future reference 😄

**Comment by toreylittlefield** [comment]
@ranegray I took a look at this and I apologize it is working for me. Can you adjust the style to make the map fit the entire viewport?
